### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by Liu-Kai-1991** [scala-js/scalajs-tutorial#13]
Git clone this branch and revert to step 3. Showing this error.

/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=51029,suspend=n,server=y -server -Xmx768M -XX:MaxPermSize=384M -Didea.runid=7.0.0+61-051fb9ba -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" -jar "/Users/kailiu/Library/Application Support/IdeaIC2017.2/Scala/launcher/sbt-launch.jar" idea-shell
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
Listening for transport dt_socket at address: 51029
[info] Loading global plugins from /Users/kailiu/.sbt/0.13/plugins
[info] Updating {file:/Users/kailiu/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.jetbrains#sbt-structure-extractor;7.0.0+61-051fb9ba ...
[info] Resolving org.jetbrains#sbt-idea-shell;1.2+7-625c26bc ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scala-sbt#sbt;0.13.16 ...
[info] Resolving org.scala-sbt#main;0.13.16 ...
[info] Resolving org.scala-sbt#actions;0.13.16 ...
[info] Resolving org.scala-sbt#classpath;0.13.16 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.16 ...
[info] Resolving org.scala-sbt#io;0.13.16 ...
[info] Resolving org.scala-sbt#control;0.13.16 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.16 ...
[info] Resolving org.scala-sbt#collections;0.13.16 ...
[info] Resolving jline#jline;2.14.4 ...
[info] Resolving org.scala-sbt#api;0.13.16 ...
[info] Resolving org.scala-sbt#classfile;0.13.16 ...
[info] Resolving org.scala-sbt#logging;0.13.16 ...
[info] Resolving org.scala-sbt#process;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.16 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.16 ...
[info] Resolving org.scala-sbt#relation;0.13.16 ...
[info] Resolving org.scala-sbt#compile;0.13.16 ...
[info] Resolving org.scala-sbt#persist;0.13.16 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.16 ...
[info] Resolving org.scala-sbt#ivy;0.13.16 ...
[info] Resolving org.scala-sbt#cross;0.13.16 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.16 ...
[info] Resolving org.scala-sbt#task-system;0.13.16 ...
[info] Resolving org.scala-sbt#tasks;0.13.16 ...
[info] Resolving org.scala-sbt#tracking;0.13.16 ...
[info] Resolving org.scala-sbt#cache;0.13.16 ...
[info] Resolving org.scala-sbt#testing;0.13.16 ...
[info] Resolving org.scala-sbt#test-agent;0.13.16 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.16 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.16 ...
[info] Resolving org.scala-sbt#command;0.13.16 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.16 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/kailiu/Documents/project/scalajs-tutorial/project
[info] Updating {file:/Users/kailiu/Documents/project/scalajs-tutorial/project/}scalajs-tutorial-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
[info] Resolving org.jetbrains#sbt-structure-extractor;7.0.0+61-051fb9ba ...
[info] Resolving org.jetbrains#sbt-idea-shell;1.2+7-625c26bc ...
[info] Resolving org.scala-js#sbt-scalajs;0.6.20 ...
[info] Resolving org.scala-js#scalajs-tools_2.10;0.6.20 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scala-js#scalajs-ir_2.10;0.6.20 ...
[info] Resolving org.scala-js#closure-compiler-java-6;v20160517 ...
[info] Resolving org.scala-js#closure-compiler-externs-java-6;v20160517 ...
[info] Resolving args4j#args4j;2.0.26 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.protobuf#protobuf-java;2.5.0 ...
[info] Resolving com.google.code.gson#gson;2.2.4 ...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Resolving com.googlecode.json-simple#json-simple;1.1.1 ...
[info] Resolving org.scala-js#scalajs-js-envs_2.10;0.6.20 ...
[info] Resolving io.apigee#rhino;1.7R5pre4 ...
[info] Resolving org.webjars#envjs;1.2 ...
[info] Resolving org.scala-js#scalajs-sbt-test-adapter_2.10;0.6.20 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#sbt;0.13.16 ...
[info] Resolving org.scala-sbt#main;0.13.16 ...
[info] Resolving org.scala-sbt#actions;0.13.16 ...
[info] Resolving org.scala-sbt#classpath;0.13.16 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.16 ...
[info] Resolving org.scala-sbt#io;0.13.16 ...
[info] Resolving org.scala-sbt#control;0.13.16 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.16 ...
[info] Resolving org.scala-sbt#collections;0.13.16 ...
[info] Resolving jline#jline;2.14.4 ...
[info] Resolving org.scala-sbt#api;0.13.16 ...
[info] Resolving org.scala-sbt#classfile;0.13.16 ...
[info] Resolving org.scala-sbt#logging;0.13.16 ...
[info] Resolving org.scala-sbt#process;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.16 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.16 ...
[info] Resolving org.scala-sbt#relation;0.13.16 ...
[info] Resolving org.scala-sbt#compile;0.13.16 ...
[info] Resolving org.scala-sbt#persist;0.13.16 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.16 ...
[info] Resolving org.scala-sbt#ivy;0.13.16 ...
[info] Resolving org.scala-sbt#cross;0.13.16 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.16 ...
[info] Resolving org.scala-sbt#task-system;0.13.16 ...
[info] Resolving org.scala-sbt#tasks;0.13.16 ...
[info] Resolving org.scala-sbt#tracking;0.13.16 ...
[info] Resolving org.scala-sbt#cache;0.13.16 ...
[info] Resolving org.scala-sbt#testing;0.13.16 ...
[info] Resolving org.scala-sbt#test-agent;0.13.16 ...
[info] Resolving org.scala-sbt#main-settings;0.13.16 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.16 ...
[info] Resolving org.scala-sbt#command;0.13.16 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.16 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.16 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to Scala.js Tutorial (in build file:/Users/kailiu/Documents/project/scalajs-tutorial/)
[IJ]> run
[info] Compiling 1 Scala source to /Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.12.2. Compiling...
[info]   Compilation completed in 13.853 s
[info] Fast optimizing /Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/scala-js-tutorial-fastopt.js
[info] Running tutorial.webapp.TutorialApp
[error] /Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/scala-js-tutorial-fastopt.js:1227
[error]   this.appendPar__Lorg_scalajs_dom_raw_Node__T__V($m_Lorg_scalajs_dom_package$().document__Lorg_scalajs_dom_raw_HTMLDocument().body, "Hello World")
[error]                                                                                                                               ^
[error] 
[error] TypeError: Cannot read property 'body' of undefined
[error]     at $c_Ltutorial_webapp_TutorialApp$.main__AT__V (/Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/file:/Users/kailiu/Documents/project/scalajs-tutorial/src/main/scala/tutorial/webapp/TutorialApp.scala:8:24)
[error]     at Object.<anonymous> (/Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/scala-js-tutorial-fastopt.js:2675:36)
[error]     at Object.<anonymous> (/Users/kailiu/Documents/project/scalajs-tutorial/target/scala-2.12/scala-js-tutorial-fastopt.js:2676:4)
[error]     at Module._compile (module.js:570:32)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:119)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:168)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:787)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$76$$anonfun$apply$51$$anonfun$apply$52.apply(ScalaJSPluginInternal.scala:939)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$76$$anonfun$apply$51$$anonfun$apply$52.apply(ScalaJSPluginInternal.scala:933)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] Total time: 20 s, completed Sep 2, 2017 9:11:24 AM
[IJ]>

**Comment by sjrd** [comment]
From step 3 onwards, the project does not `run` anymore from sbt. It only runs in the browser. You need to continue the tutorial as written until Step 6 to get it into a shape that can `run` in sbt again.
