### ISSUE TITLE
Main method not found in class tutorial.webapp.TutorialApp when run in Activator 

### ISSUE THREAD

**Issue by cloudarch** [scala-js/scalajs-tutorial#7]
Hi,
I downloaded the folder, compiled & ran it in Activator 1.3.2 - I hit the error below. Appreciate any pointers. 
 
Error: Main method not found in class tutorial.webapp.TutorialApp, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

**Comment by gzm0** [comment]
Could you make this work? Please let us know what was wrong.

**Comment by cloudarch** [comment]
Hi Tobias, I ran the tutorial from Activator terminal console vs Activator UI - I dont see the error any more. However I am still not able to launch the HTML scalajs-tutorial-fastopt.html from my browser (when I navigate to project home folder and click on html it does nothing). Do I need to deploy the WAR file to web server to see the HTML and generate JS file in action?

**Comment by gzm0** [comment]
You do not need an http server (also, there is no WAR file). But you'll need to generate the JavaScript by calling `fastOptJS` in sbt.

**Comment by gzm0** [comment]
See Step 2 of the [tutorial][1].

[1]: http://www.scala-js.org/doc/tutorial.html

**Comment by cloudarch** [comment]
I re-ran the fastOptJS, i see the generated js files however when I open scalajs-tutorial-fastopt.html it does nothing, just a blank screen.

 user$ activator
[info] Loading project definition from /Users/user/workspace/Play/X-App/project/project
[info] Updating {file:/Users/user/workspace/Play/X-App/project/project/}x-app-build-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/user/workspace/Play/X-App/project
[info] Set current project to Scala.js Tutorial (in build file:/Users/user/workspace/Play/X-App/)
> run
[info] Running tutorial.webapp.TutorialApp
[success] Total time: 1 s, completed Apr 30, 2015 1:00:59 PM
> fastOptJS
[success] Total time: 0 s, completed Apr 30, 2015 1:01:03 PM
> run
[info] Running tutorial.webapp.TutorialApp
[success] Total time: 1 s, completed Apr 30, 2015 1:01:05 PM
>

**Comment by cloudarch** [comment]
Test results seems to work fine - just launch from Web browser (chrome/firefox) does nothing.

[info] 1/3     tutorial.webapp.TutorialTest.HelloWorld		Success
[info] 2/3     tutorial.webapp.TutorialTest.ButtonClick		Success
[info] 3/3     tutorial.webapp.TutorialTest		Success
[info] -----------------------------------Results-----------------------------------
[info] tutorial.webapp.TutorialTest		Success
[info]     HelloWorld		Success
[info]     ButtonClick		Success
[info] 
[info] Tests: 3
[info] Passed: 3
[info] Failed: 0
[success] Total time: 7 s, completed Apr 30, 2015 1:06:39 PM

**Comment by cloudarch** [comment]
Also I see the Java script error in console:
no element found keepalive.owa:1:1
T 
TypeError: (intermediate value).tutorial is undefined scala-js-tutorial-launcher.js:2:0
TypeError: this.controller is undefined browserPlacesViews.js:238:0
TypeError: (intermediate value).tutorial is undefined scala-js-tutorial-launcher.js:2:0
TypeError: (intermediate value).tutorial is undefined scala-js-tutorial-launcher.js:2:0
no element found keepalive.owa:1:1
TypeError: (intermediate value).tutorial is undefined

**Comment by cloudarch** [comment]
Opened a new issue to track the above error.
